services:
  db:
    image: postgres:17-alpine
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS__PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
      REDIS_SAVE: "60 1"
      REDIS_LOGLEVEL: "warning"
    command: >
      sh -c '
        redis-server
        --save "$${REDIS_SAVE}"
        --loglevel "$${REDIS_LOGLEVEL}"
        ${REDIS_PASSWORD:+--requirepass "$${REDIS__PASSWORD}"}
      '
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS__PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
